server:
  port: 8081
spring:
  data:
    mongodb:
      authentication-database: admin
      port: 27017
      host: localhost
      database: customers_database
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root
