#spring.jpa.defer-datasource-initialization=true

#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:invoiceDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 
# P치rametros de conexi칩n a Eureka Server
# A침adir esta "eureka.instance.hostname: localhost" para apuntar a "localhost" durante la conexion. Ej: si se tiene docker, este apunta a 
# "host.docker.internal" en ves de localhost, lo que har치 que eureka no pueda encontrar nuestros servicios con Feign.
# Es necesario la linea mencionada en todos los archivos de configuracion de los microservicios (proyectos).
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
            
feign:
    hystrix:
        enabled: true # Habilitrar Hystrix
    circuitbreaker:
        enabled: true
    client:
        config:
            default:
                connectTimeout: 160000000
                readTimeout: 160000000
hystrix:
    dashboard:
        proxy-stream-allow-list: "*"
management: # Habilitar Actuator
    endpoints:
        web:
            exposure:
                include: "*"
